# Site settings
title: Gil Chen-Zion
email: gil.chenzion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Javascript, Node, PHP Developer.
  Currently at Thrillist.com.
  Co-Organizer for the NYJavascript Meetup.
  NY Tech Advocate.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gilchen-zion.com" # the base hostname & protocol for your site
twitter_username: gilcz2
github_username:  gilchenzion
analytics : "UA-66633509-1"
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
